export const IpcChannels = {
  BOT_STATUS: 'bot:status',
  BOT_STATUS_CHANGED: 'bot:status-changed',
  MUTE_ALL: 'bot:mute-all',
  UNMUTE_ALL: 'bot:unmute-all',
  GET_CONFIG: 'config:get',
  SAVE_CONFIG: 'config:save',
  GET_TARGET_INFO: 'target:info',
  GET_PRESETS_INFO: 'presets:info',
  SET_ACTIVE_PRESET: 'config:set-active-preset',
  CONFIG_CHANGED: 'config:changed',
  GET_RUNTIME_CONFIG: 'runtime:get',
  WINDOW_FIT_CONTENT: 'window:fit-content',
  WINDOW_CLOSE: 'window:close',
  OPEN_SETTINGS: 'window:open-settings',
  GET_OPERATION_HISTORY: 'history:get',
  GET_STORAGE_INFO: 'storage:info',
  PICK_DATA_DIR: 'storage:pick',
  CHANGE_DATA_DIR: 'storage:change',
  GET_APP_INFO: 'app:info',
  GET_HELP_CONTENT: 'help:content',
  OPEN_HELP: 'help:open',
  OPEN_CONTACT: 'contact:open',
  SUBMIT_CONTACT: 'contact:submit',
  GET_UPDATE_STATUS: 'update:status',
  CHECK_FOR_UPDATES: 'update:check',
  DOWNLOAD_UPDATE: 'update:download',
  INSTALL_UPDATE: 'update:install',
  UPDATE_STATUS_CHANGED: 'update:status-changed',
} as const;

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels];
